import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import ProtectedLayout from '../components/ProtectedLayout';
import { useAuth } from '../context/AuthContext';
import { useConfirm } from '../context/ConfirmContext';
import { deleteReport, getAllReports, getReports } from '../utils/propertyStorage';
import { downloadReportPdf } from '../utils/reportDocument';

export default function Reports() {
  const { user, profile } = useAuth();
  const confirm = useConfirm();
  const isAdmin = user?.role === 'Administrator' || profile?.investorType === 'Administrator';
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let active = true;

    async function loadReports() {
      if (!user?.uid) return;
      setLoading(true);
      setError('');

      try {
        const result = isAdmin ? await getAllReports() : await getReports(user.uid);
        if (active) setReports(Array.isArray(result) ? result : []);
      } catch (fetchError) {
        if (active) {
          setReports([]);
          setError(fetchError.message || 'Unable to load reports.');
        }
      } finally {
        if (active) setLoading(false);
      }
    }

    loadReports();
    return () => {
      active = false;
    };
  }, [user?.uid, isAdmin]);

  async function handleDelete(id) {
    const confirmed = await confirm('Delete this report? This action cannot be undone.', {
      title: 'Delete Report',
      confirmLabel: 'Delete',
      danger: true,
    });
    if (!confirmed) return;
    try {
      await deleteReport(user.uid, id);
      const refreshedReports = isAdmin ? await getAllReports() : await getReports(user.uid);
      setReports(Array.isArray(refreshedReports) ? refreshedReports : []);
      toast.success('Report deleted.');
    } catch (error) {
      toast.error(error.message || 'Unable to delete report.');
    }
  }

  function handleDownload(report) {
    downloadReportPdf(report);
    toast.success('PDF downloaded.');
  }

  return (
    <ProtectedLayout title="Reports" subtitle="View, download, and manage your generated investment analyses.">
      <div className="reports-shell">
        <div className="glass-card report-card">
          <div className="card-head">
            <div>
              <p className="eyebrow">Analytics</p>
              <h4>Generated analyses</h4>
            </div>
          </div>

          {loading ? (
            <div className="empty-state">
              <h4>Loading reports...</h4>
              <p>Your generated analyses will appear here shortly.</p>
            </div>
          ) : error ? (
            <div className="empty-state error-state" role="alert">
              <h4>Reports could not be loaded</h4>
              <p>{error}</p>
            </div>
          ) : reports.length === 0 ? (
            <div className="empty-state">
              <div className="empty-icon">📄</div>
              <h4>No reports generated yet</h4>
              <p>Analyze a property in the calculator to generate your first report.</p>
            </div>
          ) : (
            <div className="table-shell">
              <table>
                <thead>
                  <tr>
                    <th>Property</th>
                    <th>Date</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((report) => (
                    <tr key={report.id}>
                      <td>{report.propertyName}</td>
                      <td>{report.analysisDate || new Date(report.createdAt).toLocaleDateString()}</td>
                      <td>{report.generatedBy || report.userName || 'Investor'}</td>
                      <td>
                        <button className="table-action download-btn" onClick={() => handleDownload(report)}>⬇ Download PDF</button>
                        <button className="table-action" onClick={() => handleDelete(report.id)}>Delete Report</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </ProtectedLayout>
  );
}